version: '3.1'

services:

  redis:
    image: redislabs/rejson:latest
    ports: 
      - 6379:6379
    networks:
      - dummynetwork
  
  bes:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - redis
    networks:
      - dummynetwork
    environment:
      - REDIS_HOST=redis

  fes:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - bes
    networks:
      - dummynetwork

  ngrok:
    image: wernight/ngrok
    container_name: "ngrok"
    depends_on:
      - bes
      - fes
      - redis
    entrypoint: sh -c 'ngrok http bes:5000 --log=stdout & ngrok http fes:80 --log=stdout & ngrok tcp redis:6379 --log=stdout'
    environment:
      NGROK_AUTHTOKEN: "2iFtH6fWYMPqXMjJpUeXSlSjvEl_2HJtsCmUL5sqZ1SrZy3Sa"
      NGROK_REGION: "us"

networks:
  dummynetwork:
    driver: bridge
